# fly.toml app configuration file generated for hotels-data-merge on 2023-07-25T01:02:18+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hotels-data-merge"
primary_region = "sin"
console_command = "/rails/bin/rails console"

[deploy]
  release_command = "./bin/rails db:prepare"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[env]
  SUPPLIER_API_URL = "https://5f2be0b4ffc88500167b85a0.mockapi.io/suppliers/"
